In [19]:
import numpy as np

# Numpy Operations
### Array with array 
### Array with scalars
### Universal Array Funcations

In [5]:
array_one = np.arange(0,10)
array_two = np.arange(0,10)

In [7]:
array_one  + array_two

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
array_one * array_two 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
array_one +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
array_one / array_two

/tmp/ipykernel_108945/863916949.py:1: RuntimeWarning: invalid value encountered in divide
  array_one / array_two


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
array_two *5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
array_two.sum()

45

In [17]:
array_one.min()

0

In [18]:
array_one.mean()

4.5

In [20]:
array_one / array_one

/tmp/ipykernel_108945/1396494089.py:1: RuntimeWarning: invalid value encountered in divide
  array_one / array_one


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
np.nan

nan

In [22]:
np.square(array_one)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
np.sqrt(array_one)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [24]:
np.add(array_one,array_two)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.multiply(array_one,array_two)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])