### Numpy

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
a[0]

1

In [8]:
a[0]=10

In [9]:
a[0]

10

In [12]:
a[::-1]

array([ 3,  2, 10])

In [13]:
a

array([10,  2,  3])

In [14]:
a.ndim

1

In [15]:
a.shape

(3,)

In [16]:
a.dtype

dtype('int64')

In [17]:
a.size

3

### How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [27]:
np.zeros(4)

array([0., 0., 0., 0.])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones(1)

array([1.])

In [32]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.empty((3,4))

array([[1.36657703e-316, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.12465777e-312, 1.01855798e-312, 1.23075756e-312,
        1.06099790e-312],
       [1.06099790e-312, 9.76118064e-313, 1.12465777e-312,
        1.90979621e-312]])

In [41]:
np.empty((3,4))

array([[1.36657703e-316, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.12465777e-312, 1.01855798e-312, 1.23075756e-312,
        1.06099790e-312],
       [1.06099790e-312, 9.76118064e-313, 1.12465777e-312,
        1.90979621e-312]])

In [43]:
np.empty((3,4)) == np.empty((3,4))

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [46]:
np.zeros(1) ==np.zeros(1)

array([ True])

In [47]:
np.arange(3)

array([0, 1, 2])

In [49]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
n = np.linspace(0,5,50) # linear space between the element of the array

In [60]:
n[0]  -n [1]

-0.10204081632653061

In [61]:
n[1]-n[2]

-0.10204081632653061

In [64]:
np.sort(list((2,34,56,7,89)))

array([ 2,  7, 34, 56, 89])

In [67]:
array_one = np.array([1,2])  
array_two = np.array([4,5])

In [71]:
np.concatenate((array_one,array_two))

array([1, 2, 4, 5])

In [85]:
np.random.random((10,2))

array([[0.02423899, 0.78254123],
       [0.15239091, 0.48044103],
       [0.37559885, 0.28501504],
       [0.58497323, 0.82761387],
       [0.25570791, 0.65956257],
       [0.83142241, 0.28414155],
       [0.74553034, 0.29187209],
       [0.90284713, 0.09326022],
       [0.72014731, 0.17277985],
       [0.87948351, 0.42069587]])

In [87]:
np.random.rand(3)

array([0.58957425, 0.36074424, 0.49296585])

In [88]:
np.random.rand(1,4)

array([[0.49138397, 0.68047517, 0.55945105, 0.90861616]])

In [92]:
np.random.randn(1,4)

array([[-0.19121281, -0.93709641,  0.81732516, -0.73736496]])

In [97]:
np.random.randint(1,100,(5,4))

array([[ 3, 27, 68, 99],
       [ 3, 29,  9,  9],
       [51, 77, 91, 22],
       [15, 48, 68, 70],
       [32, 23, 10, 31]])

In [103]:
array_four = np.random.randint(0,50,20)

In [104]:
array_four

array([ 2, 45,  1, 28,  1, 45, 14, 28, 24, 19, 12,  2, 28, 30, 22, 46, 28,
       10, 42,  3])

In [109]:
np.reshape(array_four,(4,5))

array([[ 2, 45,  1, 28,  1],
       [45, 14, 28, 24, 19],
       [12,  2, 28, 30, 22],
       [46, 28, 10, 42,  3]])

In [111]:
array_four.min()

1

In [112]:
array_four.max()

46

In [113]:
array_four.argmax()

15

In [114]:
array_four.argmin()

2

In [118]:
array_four.size

20

In [119]:
array_four.ndim

1

In [121]:
array_four[::-1]

array([ 3, 42, 10, 28, 46, 22, 30, 28,  2, 12, 19, 24, 28, 14, 45,  1, 28,
        1, 45,  2])

In [122]:
array_four

array([ 2, 45,  1, 28,  1, 45, 14, 28, 24, 19, 12,  2, 28, 30, 22, 46, 28,
       10, 42,  3])

In [123]:
np.flip(array_four)

array([ 3, 42, 10, 28, 46, 22, 30, 28,  2, 12, 19, 24, 28, 14, 45,  1, 28,
        1, 45,  2])

In [124]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [125]:
np.unique(array_four)

array([ 1,  2,  3, 10, 12, 14, 19, 22, 24, 28, 30, 42, 45, 46])

In [129]:
a=[2,34,5,55,5,5]
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[1 3 1 1]


In [131]:
unique_values
occurrence_count

array([1, 3, 1, 1])

In [133]:
np.random.randint(1,4,5)

array([2, 2, 3, 1, 3])

## Numpy indexing and selection 

In [134]:
arr = np.arange(0,40)

In [136]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [137]:
arr[:5]

array([0, 1, 2, 3, 4])

In [148]:
arr[-1:-4:-1]

array([39, 38, 37])

In [153]:
arr[0:4]=100

In [154]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

In [155]:
new_arr =arr[0:10]

In [156]:
new_arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [159]:
new_arr[:]=100

In [160]:
new_arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [161]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

In [162]:
copy_arr =  arr.copy()

In [164]:
copy_arr[:]=1000

In [165]:
copy_arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [166]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39])

### Index of 2D-Array

In [183]:
array_2d = np.linspace(1,10,10).reshape(5,2)

In [184]:
array_2d.shape

(5, 2)

In [185]:
array_2d.ndim

2

In [195]:
array_2d[0][1]

2.0

In [200]:
array_2d[:3]

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [210]:
arr = np.arange(0,50).reshape(5,10)

In [211]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [213]:
arr[1,0]

10

In [221]:
arr[1:,2:]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [222]:
arr[:,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [227]:
np.arange(0,5) + np.arange(0,5)

array([0, 2, 4, 6, 8])

In [233]:
arr[arr >5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [234]:
arr[arr<3]

array([0, 1, 2])